Modification:
- Dockerfile adding Node binaries
- extra lib/reset-build which updates the images
- postAccount.js:
	+ uses ES Module with 'fs', 'path', 'fileURLToPath' and custom
	  module with paths
	+ uses process.env; so to invoke makePostRequest run:
	'node --env-file=.env src/public/fg/postAccount.js'
	+ postUrl fallsback to 'localhost:8000/accounts' when run
	  locally; so locally use:
	  'node src/public/fg/postAccount.js' or directly codeRunner
	  from VSCode

diff --git a/scripts/lib/compose b/scripts/lib/compose
--- a/scripts/lib/compose
+++ b/scripts/lib/compose
@@ -2,6 +2,11 @@
 
 set -e
 
+BLUE='\033[0;34m'
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+NC='\033[0m'
+
 # arg="${1:?[error]: ArgumentRequired. [up/down]}"
 arg=${1:-}
 
@@ -19,7 +24,7 @@ PG_PASSWORD="${DB_PASSWORD}"
 
 arg-logic() {
     if [[ "$arg" != "up" && "$arg" != "down" ]]; then
-        echo "[error]: InvalidArgument. [up/down]" >&2
+        echo -e "${RED}[error]:\tInvalidArgument \tLiteral[up, down]${NC}" >&2
         exit 1
 
     elif [[ "$arg" == "up" ]]; then
@@ -27,15 +32,15 @@ arg-logic() {
         docker compose --env-file ../.env up -d
         # proper health check loop:
         until docker exec $DB_SERVICE pg_isready -U $PG_USER -h $PG_HOST >/dev/null 2>&1; do
-            echo "[debug]: __waiting_for_db__" >&2
+            echo -e "${BLUE}[debug]: \t__waiting_for_db__${NC}" >&2
             sleep 1
         done
-        echo "[info]: __network_up__"
+        echo -e "${GREEN}[info]: \t__network_up__${NC}"
 
     else
         cd "docker"
         docker compose --env-file ../.env down
-        echo "[info]: __network_down__"
+        echo -e "${GREEN}[info]: \t__network_down__${NC}"
     fi
 }
 
